"""empty message

Revision ID: caa8be10855a
Revises: 
Create Date: 2025-11-09 17:52:45.878660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa8be10855a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('count_students', sa.Integer(), nullable=False),
    sa.Column('count_campus', sa.Integer(), nullable=False),
    sa.Column('count_branches', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('institute', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('cost_of_education', sa.Integer(), nullable=False),
    sa.Column('total_hours', sa.Integer(), nullable=False),
    sa.Column('practical_hours', sa.Integer(), nullable=False),
    sa.Column('average_hours', sa.Integer(), nullable=False),
    sa.Column('count_exams', sa.Integer(), nullable=False),
    sa.Column('count_coursework', sa.Integer(), nullable=False),
    sa.Column('count_budget', sa.Integer(), nullable=False),
    sa.Column('min_mark', sa.Integer(), nullable=False),
    sa.Column('average_mark', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specs')
    op.drop_table('universities')
    # ### end Alembic commands ###
